// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9pFXFNU-EcqOlpGfC0DM-HwyezrhTicI',
    appId: '1:138078072380:web:2a19360d89730bbce95d39',
    messagingSenderId: '138078072380',
    projectId: 'master-mold-fddfd',
    authDomain: 'master-mold-fddfd.firebaseapp.com',
    storageBucket: 'master-mold-fddfd.appspot.com',
    measurementId: 'G-NQ3T9DZ38F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV1sJt7iTh2U7ic3HdBRjshglFKkB8r_8',
    appId: '1:138078072380:android:5bfb586307c44367e95d39',
    messagingSenderId: '138078072380',
    projectId: 'master-mold-fddfd',
    storageBucket: 'master-mold-fddfd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWUvVAiYkdYZmeL3ypJq46gwRgYARhTHc',
    appId: '1:138078072380:ios:fcc5548e9f0a9fcce95d39',
    messagingSenderId: '138078072380',
    projectId: 'master-mold-fddfd',
    storageBucket: 'master-mold-fddfd.appspot.com',
    iosBundleId: 'com.example.mastermold',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWUvVAiYkdYZmeL3ypJq46gwRgYARhTHc',
    appId: '1:138078072380:ios:fcc5548e9f0a9fcce95d39',
    messagingSenderId: '138078072380',
    projectId: 'master-mold-fddfd',
    storageBucket: 'master-mold-fddfd.appspot.com',
    iosBundleId: 'com.example.mastermold',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9pFXFNU-EcqOlpGfC0DM-HwyezrhTicI',
    appId: '1:138078072380:web:573bcdf37cdbb8e0e95d39',
    messagingSenderId: '138078072380',
    projectId: 'master-mold-fddfd',
    authDomain: 'master-mold-fddfd.firebaseapp.com',
    storageBucket: 'master-mold-fddfd.appspot.com',
    measurementId: 'G-VR8R9BJLHC',
  );
}
